services:
  - type: web
    name: video-quiz
    env: node
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This indicates that DATABASE_URL is set in the Render dashboard
